python /home/jack/flower_vla_calvin/preprocess/convert_with_forcehistory_smoothfirst.py \
  --input /data2/jack/2026_05_AGI/default_lsm/lsm/multi \
  --pkl_glob "**/*.pkl" \
  --output_root /home/jack/flower_vla_calvin/multi_task_dataset_real_robot_13d_norm_force_history_butter_first \
  --robot_obs_format real_robot \
  --normalize_state \
  --include_right_force_history \
  --normalize_ft_history \
  --ft_history_filter butterworth \
  --ft_history_sample_rate_hz 100.0 \
  --ft_history_cutoff_hz 10.0 \
  --ft_history_filter_order 2 \
  --action_source raw \
  --trailing_keep 5 \
  --val_ratio 0